// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWYZCEeIEGcXjrydf38cQnd4s4cSSbO4',
    appId: '1:1002128791685:web:02a396b38acf2ee181f1ec',
    messagingSenderId: '1002128791685',
    projectId: 'weight-tracker-42dc0',
    authDomain: 'weight-tracker-42dc0.firebaseapp.com',
    storageBucket: 'weight-tracker-42dc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDwO7KiNZvi_-W7vkXRMCaujZHjGM9Z0A',
    appId: '1:1002128791685:android:b3afbb32ce129c5181f1ec',
    messagingSenderId: '1002128791685',
    projectId: 'weight-tracker-42dc0',
    storageBucket: 'weight-tracker-42dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_GLA96gFcEJjWkgGTnyrwJZOOGFmYRU',
    appId: '1:1002128791685:ios:a7f1f781de7a65db81f1ec',
    messagingSenderId: '1002128791685',
    projectId: 'weight-tracker-42dc0',
    storageBucket: 'weight-tracker-42dc0.appspot.com',
    iosBundleId: 'com.rolufs.weightTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh_GLA96gFcEJjWkgGTnyrwJZOOGFmYRU',
    appId: '1:1002128791685:ios:6ce50f350dc21fb381f1ec',
    messagingSenderId: '1002128791685',
    projectId: 'weight-tracker-42dc0',
    storageBucket: 'weight-tracker-42dc0.appspot.com',
    iosBundleId: 'com.example.weightTracker.RunnerTests',
  );
}
